projects:
  - name: epaytest
    queues_default:
      notify_base: "http://10.165.59.160:9981"
      notify_timeout: 5
      retry_times: 2
      retry_duration: 30
      binding_exchange: epay
    queues:
      - queue_name: "ordernotify"
        notify_path: "/notify/order"
        routing_key:
          - "ordernotify"
      #- queue_name: "orders"
      #  notify_path: "/test.html"
      #  routing_key:
      #    - "order"